parameters:
- name: 'arch'
  type: string
- name: 'pool'
  type: object
  default: {}
- name: 'containerImage'
  type: string
- name: 'codeCoverage'
  type: boolean
  default: false

jobs:
- job:
  displayName: ${{ parameters.arch }}
  timeoutInMinutes: 60
  pool: ${{ parameters.pool }}

  container:
    image: ${{ parameters.containerImage }}

  steps:
  - ${{ if and(eq(parameters.arch, 'amd64'), parameters.codeCoverage) }}:
    - script: |
        wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
        sudo dpkg -i packages-microsoft-prod.deb
        rm packages-microsoft-prod.deb
        sudo apt-get update
        sudo apt-get install -y apt-transport-https
        sudo apt-get install -y dotnet-sdk-6.0
      displayName: install .Net
  - script: |
      sudo apt-get install -y \
          libboost-system-dev \
          libboost-thread-dev \
          googletest \
          libgtest-dev \
          libgmock-dev \
          libhiredis-dev \
          libnl-3-dev \
          libnl-route-3-dev \
          libnl-genl-3-dev \
          libnl-nf-3-dev

    displayName: "Install dependencies"
  - checkout: self
    clean: true
    submodules: true
  - task: DownloadPipelineArtifact@2
    inputs:
      source: specific
      project: build
      pipeline: 9
      ${{ if eq(parameters.arch, 'amd64') }}:
        artifact: sonic-swss-common
      ${{ else }}:
        artifact: sonic-swss-common.${{ parameters.arch }}
      runVersion: 'latestFromBranch'
      runBranch: 'refs/heads/master'
      path: '$(Build.SourcesDirectory)/sonic-swss-common'
    displayName: "Download sonic swss common deb packages"
  - script: |
        sudo dpkg -i sonic-swss-common/libswsscommon_1.0.0_${{ parameters.arch }}.deb
        sudo dpkg -i sonic-swss-common/libswsscommon-dev_1.0.0_${{ parameters.arch }}.deb
    displayName: "Install sonic swss common"
  - script: |
      rm ../*.deb
      dpkg-buildpackage -us -uc -b -j$(nproc)
      cp ../*.deb $(Build.ArtifactStagingDirectory)
    displayName: "Compile sonic dhcp-relay"
  - publish: $(Build.ArtifactStagingDirectory)
    artifact: sonic-dhcp-relay.${{ parameters.arch }}
    displayName: "Archive dhcp-relay debian packages"
  - task: PublishTestResults@2
    inputs:
      testResultsFiles: build-test/dhcp6relay-test-test-result.xml
  - ${{ if and(eq(parameters.arch, 'amd64'), parameters.codeCoverage) }}:
    - task: PublishCodeCoverageResults@1
      inputs:
        summaryFileLocation: build-test/dhcp6relay-test-code-coverage.xml
        pathToSources: $(Build.SourcesDirectory)
        reportDirectory: $(Build.SourcesDirectory)/build-test
        codeCoverageTool: 'Cobertura'
